### ISSUE TITLE
Not well-formed (invalid token)

### ISSUE THREAD

**Issue by kingkong-cmd** [sopherapps/xml_stream#2]
I'm parsing an XML-file where i am able to loop through many items fitst, but for one item I get the below error, and it breaks the whole loop. Is there anyway I can make the loop continue and just skip the erroneus item when the error occurs?

Loop looks like this:

`for item in read_xml_file(filename, records_tag='product'):`
` ## do stuff in loop

Error stack trace looks like this:
```
    for item in read_xml_file(filename, records_tag='product'):
  File "...\venv\Lib\site-packages\xml_stream\__init__.py", line 24, in read_xml_file
    for event, element in context:
  File "...Programs\Python\Python39\Lib\xml\etree\ElementTree.py", line 1254, in iterator  
    yield from pullparser.read_events()
  File "...Programs\Python\Python39\Lib\xml\etree\ElementTree.py", line 1329, in read_events
    raise event
  File "...Programs\Python\Python39\Lib\xml\etree\ElementTree.py", line 1301, in feed      
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 3758, column 1966
```

**Comment by Tinitto** [comment]
Hey @kingkong-cmd , sorry, I have not been available because for some reason, github does not send me notifications. I am not sure which account setting I messed up.

For your issue, have you tried changing the for-loop to something like a 'while' loop, then accessing the iterator got from 'read_xml_file' using 'next()' but wrapped in a try-except to capture 'xml.etree.ElementTree.ParseError' errors?

something like:

```python
item_itr = read_xml_file(filename, records_tag='product')
item = None
while(item is not False):
    try:
        item = next(item_itr, False)
        ## do stuff with item, taking note that item could be False.
    except xml.etree.ElementTree.ParseError:
        pass
```

**Comment by Tinitto** [comment]
I am closing this as it seems not to be upto the library to handle this for the programmer.
